"""Unit tests for Fire CA model (dynamics/fire_ca.py).

Tests determinism, spread rules, smoke generation, burnout, and force_cell_state.
"""

from __future__ import annotations

import numpy as np
import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_fire_model(
    map_size: int = 20,
    seed: int = 42,
    n_ignition: int = 2,
):
    """Create a FireSpreadModel for testing (no wind — FD-5)."""
    from uavbench.dynamics.fire_ca import FireSpreadModel

    rng = np.random.default_rng(seed)
    return FireSpreadModel(
        map_shape=(map_size, map_size),
        rng=rng,
        n_ignition=n_ignition,
    )


# ===========================================================================
# Determinism
# ===========================================================================


class TestFireCADeterminism:
    """Fire CA produces identical results for identical seeds."""

    def test_same_seed_same_state(self):
        """Two models with same seed produce identical fire_mask after N steps."""
        model_a = _make_fire_model(seed=42)
        model_b = _make_fire_model(seed=42)

        for _ in range(10):
            model_a.step()
            model_b.step()

        np.testing.assert_array_equal(
            model_a.fire_mask, model_b.fire_mask,
            err_msg="Fire CA must be deterministic for same seed",
        )
        np.testing.assert_array_equal(
            model_a.smoke_mask, model_b.smoke_mask,
            err_msg="Smoke must be deterministic for same seed",
        )

    def test_different_seed_different_state(self):
        """Two models with different seeds produce different fire_mask."""
        model_a = _make_fire_model(seed=42)
        model_b = _make_fire_model(seed=99)

        for _ in range(10):
            model_a.step()
            model_b.step()

        # At least one cell should differ
        assert not np.array_equal(model_a.fire_mask, model_b.fire_mask), (
            "Different seeds should produce different fire states"
        )


# ===========================================================================
# Spread Rules
# ===========================================================================


class TestFireSpreadRules:
    """Fire spreads to adjacent cells based on stochastic rules."""

    def test_initial_ignition(self):
        """After construction, at least one cell is burning."""
        model = _make_fire_model(n_ignition=3)
        assert model.fire_mask.any(), "Fire model must have initial ignition"

    def test_fire_spreads(self):
        """After multiple steps, fire has spread beyond initial ignition."""
        model = _make_fire_model(n_ignition=2, map_size=30)
        initial_count = model.fire_mask.sum()

        for _ in range(20):
            model.step()

        # Fire should have affected more cells (burning + burned out)
        final_burning = model.fire_mask.sum()
        # Either more cells are burning, or some have burned out
        assert model.total_affected >= initial_count, (
            "Fire should spread or burn out — total affected should not decrease "
            "below initial ignition count"
        )

    def test_water_does_not_burn(self):
        """If a landuse map is provided, water cells (4) never catch fire."""
        from uavbench.dynamics.fire_ca import FireSpreadModel

        rng = np.random.default_rng(42)
        # Create landuse with left half = water (4), right half = forest (1)
        landuse = np.ones((20, 20), dtype=np.int8)
        landuse[:, :10] = 4  # water

        model = FireSpreadModel(
            map_shape=(20, 20),
            rng=rng,
            n_ignition=3,
            landuse_map=landuse,
        )

        for _ in range(30):
            model.step()

        # Water cells should never be burning
        water_burning = model.fire_mask[:, :10].any()
        assert not water_burning, "Water cells must never catch fire"


# ===========================================================================
# Smoke Generation
# ===========================================================================


class TestSmokeGeneration:
    """Burning cells produce smoke that spreads."""

    def test_smoke_mask_shape(self):
        """smoke_mask has same shape as map."""
        model = _make_fire_model(map_size=15)
        assert model.smoke_mask.shape == (15, 15)

    def test_smoke_near_fire(self):
        """After several steps, smoke exists near burning cells."""
        model = _make_fire_model(map_size=20, n_ignition=3)

        for _ in range(10):
            model.step()

        # Smoke should be non-zero somewhere
        assert model.smoke_mask.max() > 0, "Smoke should be generated by fire"

    def test_smoke_values_bounded(self):
        """Smoke values are in [0, 1]."""
        model = _make_fire_model(map_size=20, n_ignition=3)

        for _ in range(20):
            model.step()

        assert model.smoke_mask.min() >= 0.0, "Smoke must be >= 0"
        assert model.smoke_mask.max() <= 1.0, "Smoke must be <= 1"


# ===========================================================================
# Burnout
# ===========================================================================


class TestBurnout:
    """Cells eventually burn out after sustained burning."""

    def test_burnout_occurs(self):
        """After many steps, some cells should be burned out."""
        model = _make_fire_model(map_size=20, n_ignition=5)

        for _ in range(250):
            model.step()

        assert model.burned_mask.any(), (
            "After 250 steps, some cells should have burned out"
        )

    def test_burned_cells_not_burning(self):
        """Burned-out cells are not in the fire_mask."""
        model = _make_fire_model(map_size=20, n_ignition=5)

        for _ in range(250):
            model.step()

        # No cell should be both burning and burned out
        overlap = model.fire_mask & model.burned_mask
        assert not overlap.any(), "Burned-out cells must not be in fire_mask"


# ===========================================================================
# Test Hook: force_cell_state
# ===========================================================================


class TestForceState:
    """force_cell_state test hook works correctly."""

    def test_force_burning(self):
        """force_cell_state(x, y, BURNING) sets a cell to burning."""
        from uavbench.dynamics.fire_ca import BURNING, UNBURNED, FireSpreadModel

        rng = np.random.default_rng(42)
        model = FireSpreadModel(
            map_shape=(10, 10),
            rng=rng,
            n_ignition=0,  # no initial fire
        )

        assert not model.fire_mask[5, 3], "Cell should start unburned"
        model.force_cell_state(3, 5, BURNING)
        assert model.fire_mask[5, 3], "Cell should now be burning"

    def test_force_does_not_affect_others(self):
        """Forcing one cell does not affect adjacent cells."""
        from uavbench.dynamics.fire_ca import BURNING, FireSpreadModel

        rng = np.random.default_rng(42)
        model = FireSpreadModel(
            map_shape=(10, 10),
            rng=rng,
            n_ignition=0,
        )

        initial_state = model.fire_mask.copy()
        model.force_cell_state(5, 5, BURNING)

        # Only (5,5) should change
        diff = model.fire_mask != initial_state
        assert diff.sum() == 1, "Only the forced cell should change"
        assert diff[5, 5], "The forced cell should be the one that changed"


# ===========================================================================
# Properties
# ===========================================================================


class TestFireProperties:
    """Fire model properties return correct types and shapes."""

    def test_fire_mask_is_bool(self):
        model = _make_fire_model()
        assert model.fire_mask.dtype == bool

    def test_burned_mask_is_bool(self):
        model = _make_fire_model()
        assert model.burned_mask.dtype == bool

    def test_smoke_mask_is_float(self):
        model = _make_fire_model()
        assert model.smoke_mask.dtype == np.float32

    def test_total_affected_is_int(self):
        model = _make_fire_model()
        assert isinstance(model.total_affected, (int, np.integer))

    def test_masks_are_copies(self):
        """Properties return copies, not views."""
        model = _make_fire_model()
        mask1 = model.fire_mask
        mask2 = model.fire_mask
        assert mask1 is not mask2, "fire_mask should return a copy"
